### PR TITLE
YSE setting fields

### PR DESCRIPTION
**Pull request by djones1040**
[just a new script to flag setting YSE fields automatically so i don't forget](https://github.com/davecoulter/YSE_PZ/pull/181)

### CODE REVIEW

**Comment by astrophpeter** [comment]
Looks like this fixes issue #172 ?

**Comment by astrophpeter** [comment]
does it also fix issue #137 ?

**Comment by djones1040** [comment]
yeah correct, though these are all fixed in the previous pull request assuming I did things correctly

**Comment by djones1040** [comment]
yeah please do

**Review by astrophpeter — APPROVED** [review]
Looks good

**Comment by astrophpeter** [comment]
closes issue #137 #172

**Pull request merged**
